"use client";

import { useState } from "react";
import type { GeneratedScript } from "@/app/lib/types";

const FieldRow = ({ label, value, note }: { label: string; value?: string; note?: string }) => {
  if (!value?.trim()) return null;
  return (
    <div className="py-3 border-b border-[#1f1f1f] last:border-b-0">
      <p className="text-[#8a8a8a] text-xs md:text-sm uppercase tracking-[0.12em] mb-1">{label}</p>
      <p className="text-[#e2e2e2] text-sm md:text-base leading-relaxed whitespace-pre-wrap break-words">{value}</p>
      {note && <p className="text-[#555] text-[11px] mt-1 italic">{note}</p>}
    </div>
  );
};

function Card({ title, note, open, onToggle, children }: {
  title: string; note: string; open: boolean; onToggle: () => void; children: React.ReactNode;
}) {
  return (
    <section className="rounded-xl border border-[#222] bg-gradient-to-b from-[#101010] to-[#0b0b0b] overflow-hidden">
      <button onClick={onToggle} className="w-full px-4 md:px-5 py-3.5 md:py-4 text-left hover:bg-[#141414] transition-colors">
        <h3 className="text-white text-base md:text-lg font-semibold">{title}</h3>
        <p className="text-[#666] text-xs mt-1 italic">{note}</p>
      </button>
      {open && <div className="px-4 md:px-5 pb-4 md:pb-5">{children}</div>}
    </section>
  );
}

interface Props { data: GeneratedScript | null }

export function ScriptDisplay({ data }: Props) {
  console.log("data", data)
  const [open, setOpen] = useState<Record<string, boolean>>({
    meta: true,
    full: true,
    script: false,
  });

  if (!data) return null;

  const toggle = (k: string) => setOpen((p) => ({ ...p, [k]: !p[k] }));

  function downloadDoc() {
    if (!data) return;

    // ✅ Format an toàn không bị lỗi font
    const content = `# YOUTUBE SCRIPT
---------------------------------------------------------------------

## FULL SCRIPT
---------------------------------------------------------------------

${data.fullScript}


## RAW SECTIONS (Before Stitching)
---------------------------------------------------------------------

### HOOK
${data.sections.hook.text}

---------------------------------------------------------------------

### SETUP
${data.sections.setup.text}

---------------------------------------------------------------------

### CONTRADICTION
${data.sections.contradiction.text}

---------------------------------------------------------------------

### REFRAME
${data.sections.reframe.text}

---------------------------------------------------------------------

### SOLUTION
${data.sections.solution.text}

---------------------------------------------------------------------

### CLOSE
${data.sections.close.text}

---------------------------------------------------------------------

Generated by YouTube Analyzer
${new Date().toLocaleString("vi-VN")}
`;

    const blob = new Blob([content], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `youtube-script-${Date.now()}.docx`;
    a.style.display = "none";
    
    // ✅ Fix lỗi removeChild: Gắn vào DOM thật trước khi click
    document.body.appendChild(a);
    
    // Dùng setTimeout để trình duyệt có thời gian xử lý click
    setTimeout(() => {
      a.click();
      
      // Chờ thêm thời gian trước khi xóa URL và thẻ
      setTimeout(() => {
        URL.revokeObjectURL(url);
        if (document.body.contains(a)) {
          document.body.removeChild(a);
        }
      }, 100);
    }, 0);
  }

  return (
    <div className="space-y-4">
      <div className="flex justify-end">
        <button onClick={downloadDoc}
          className="px-4 py-2 bg-emerald-500/10 border border-emerald-500/30 rounded-lg text-emerald-400 hover:bg-emerald-500/20 transition-all text-sm font-medium">
          📄 Download .docx
        </button>
      </div>

      <Card title="📋 Script Meta" note="Thông tin tổng quan script" open={open.meta} onToggle={() => toggle("meta")}>
        <FieldRow label="Status" value={data.status} />
      </Card>

      <Card title="📄 Full Script" note="Script hoàn chỉnh đã được làm sẵn cho bạn" open={open.full} onToggle={() => toggle("full")}>
        <div className="bg-[#0d0d0d] border border-[#1e1e1e] rounded-lg p-4 max-h-[700px] overflow-y-auto">
          <p className="text-[#e2e2e2] text-sm leading-relaxed whitespace-pre-wrap font-mono">{data.fullScript}</p>
        </div>
      </Card>

      <Card title="🧩 Raw Sections" note="Các phần script gốc chưa được stitch" open={open.script} onToggle={() => toggle("script")}>
        <div className="space-y-6">
          <FieldRow label="🎣 Hook" value={data.sections.hook.text} />
          <FieldRow label="🏗️ Setup" value={data.sections.setup.text} />
          <FieldRow label="💥 Contradiction" value={data.sections.contradiction.text} />
          <FieldRow label="🔄 Reframe" value={data.sections.reframe.text} />
          <FieldRow label="✅ Solution" value={data.sections.solution.text} />
          <FieldRow label="🚪 Close" value={data.sections.close.text} />
        </div>
      </Card>
    </div>
  );
}